# -------------------------------------------------------------------
#          CONFIGURATION FOR TARGETED ASSEMBLY WORKFLOW
# -------------------------------------------------------------------
 
# --- Sample Configuration ---
# List your samples here. The key is the sample name (e.g., "Sample1"),
# and the value is the path and prefix of the input fastq files.
# The workflow will find all *.fastq.gz files in your path.
samples:
  Sample1: "/path/to/input/reads"
  # Sample2: "path/to/input/reads"
 
# --- External Database and Script Paths ---
# Fill in the absolute paths to your databases and scripts.
paths:
  # Database for initial read classification
  diamond_db: "/path/to/diamond/database.dmnd"
  # Database for CheckV
  checkv_db: "/path/to/checkv/"
  # Path to diamond post-processing script
  post_process_script: "scripts/post_process_diamond_v1.0.py"
 
# --- Assembler Selection ---
# Set to 'true' to run an assembler, or 'false' to skip it.
assemblers:
  metaflye: true
  penguin: true
  raven: true
  canu: true
  # Add other assemblers if needed
 
# --- General Parameters ---
params:
  threads: 24
  # Minimum contig length for PenguiN
  penguin_min_contig_len: 500
  # Minimum sequence identity for PenguiN overlaps
  penguin_min_seq_id: 0.95
  # Set genome size for canu
  canu_genome_size: 200k
  # Set DIAMOND BLASTX sensitivity for read filtering
  # options: fast, mid-sensitive, sensitive, more-sensitive, very-sensitive, ultra-sensitive
  diamond_sensitivity: sensitive

# --- Virus Selection ---
# Add any viruses you want to specifically deep-dive on
viruses_of_interest:
  # Key: A species name for the virus
  # Value: Path to the reference FASTA for that virus
  Virus_name_1: "path/to/reference/genome"
  Virus_name_2: "path/to/reference/genome"